DROP TABLE IF EXISTS Timer;
CREATE TABLE IF NOT EXISTS Timer(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    working INTEGER NOT NULL,
    breaking INTEGER NOT NULL,
    cycles TEXT NOT NULL,
    memo TEXT
);